---
- name: Register primary node
  become_user: postgres
  shell: repmgr primary register
  ignore_errors: yes
  when: ansible_hostname == "db01"

- name: Stop PostgreSQL
  systemd:
    name: postgresql
    state: stopped
  when: ansible_hostname == "db02"

- name: Clean up PostgreSQL data directory
  become_user: postgres
  file:
    path: /var/lib/postgresql/{{ pg_version }}/main
    force: yes
    state: absent
  when: ansible_hostname == "db02"

- name: Clone primary node data
  become_user: postgres
  shell: repmgr -h {{ db01_ip }} -U repmgr -d repmgr standby clone
  ignore_errors: yes
  when: ansible_hostname == "db02"

- name: Start PostgreSQL
  systemd:
    name: postgresql
    state: started
  when: ansible_hostname == "db02"

- name: Register {{ role }} node
  become_user: postgres
  shell: repmgr -h {{ db01_ip }} primary register -F
  ignore_errors: yes
  when: ansible_hostname != "db01"

- name: Start repmgrd
  become_user: postgres
  shell: repmgrd
  ignore_errors: yes
